---
title: "FerrajBubbleplot"
output: html_document
date: "2024-06-14"
---

Load relevant packages
```{r setup, include=FALSE}
library('tidyverse')
library('ggplot2')
```

Loading in data and defining what is of interest
```{r}
#datafile and inserions for analysis
Datafile <- 'BALBnotinBL6.txt'
allInsertions <-  c('MTA_Mm;', 'IAP', 'RLTR10;', 'MT2_Mm;', 'RLTR17B_Mm;')
#allInsertions <-  c('L1', 'ERVK', 'B2', 'B1',	'ERVL-MaLR',	'ERVL', 'ERV1', 'B4')
strain <- gsub("notinBL6.txt", "", Datafile)

#load data
table <- read_tsv(Datafile)
allClusters <- 1:(nrow(table(table$Cluster)))

#changeing names and depending on if cluster or group, rename
colnames(table)[colnames(table) == 'C57'] <- 'BL6'
colnames(table)[colnames(table) == 'Group order'] <- 'group'
table$cluster <- table$Cluster+1
table$cluster <- table$group

```


The log2fold calculation

```{r}

#filtering out insertions that does not belong to any group
straintable <- table
straintable$collected <- (straintable$L1 + straintable$ERVK + straintable$B2 + straintable$B1 + straintable$'ERVL-MaLR' + straintable$ERVL + straintable$ERV1 +straintable$B4)
straintable <- straintable %>% filter(collected != 0)

#calculating the average distribution across all clusters
totalcounts <- sapply(allInsertions, function(col) sum(straintable[[col]], na.rm = FALSE))


globaldf <- data.frame(x=allInsertions, counts=totalcounts)
finalmatrix <- matrix(0, nrow = length(allInsertions), ncol = length(allClusters))
rownames(finalmatrix) <- allInsertions
colnames(finalmatrix) <- allClusters


#creating nested loop as to make a table with cluster/logfold for chosen strain
for (INSx in allInsertions) {
  for (clusterx in allClusters) {
    cluster1 <- straintable %>% 
      select('FVB', 'CBA', 'BALB', 'BL6', 'cluster', allInsertions) %>% filter(cluster == clusterx )
    
    counts <- sapply(allInsertions, function(col) sum(cluster1[[col]], na.rm = FALSE))
    
    localdf <- data.frame(x=allInsertions, counts=counts)
    localdf <- localdf %>% mutate(across(where(is.numeric), ~ .x + 1)) #adding 1 to every value to avoid 0
    
    globaldf$freq <- globaldf$counts/sum(globaldf$counts)
    totallocalcounts <- sum(localdf$counts)
    localdf$expectedcounts <- totallocalcounts*globaldf$freq
    localdf$logfoldchange <- log2(localdf$counts/localdf$expectedcounts)
    
    finalmatrix[INSx, as.character(clusterx)] <- localdf$logfoldchange[which(localdf$x == INSx)]
    
  }
}

finaldf <- as.data.frame(as.table(finalmatrix))

# Rename the columns for clarity
colnames(finaldf) <- c("INSx", "Clusterx", "Log2foldchange")

```

Doing the statistical analysis 

Warnings are silenced, as there will be warnings where it finds a 0.
```{r, warning=FALSE}

#defining the chi square test function
perform_chi_square_test <- function(row) {
  matrix_data <- matrix(c(row$INSin, row$INSout, row$nonINSin, row$nonINSout), nrow = 2, byrow = TRUE)
  test_result <- chisq.test(matrix_data, correct = FALSE)
  return(test_result)
}

finalmatrix <- matrix(NA, nrow = length(allClusters), ncol = length(allInsertions))
colnames(finalmatrix) <- allInsertions
rownames(finalmatrix) <- allClusters


for (INSx in allInsertions) {
  list1 <- c()
  list2 <- c()
  list3 <- c()
  list4 <- c()
  for (clusterx in allClusters) {
    
    INSin <- table %>% filter(.data[[INSx]] == 0) %>% filter(cluster == clusterx) 
    INSout <- table %>% filter(.data[[INSx]] == 1) %>% filter(cluster == clusterx) 
    nonINSin <- table %>% filter(.data[[INSx]] == 0) %>% filter(cluster != clusterx) 
    nonINSout <- table %>% filter(.data[[INSx]] == 1) %>% filter(cluster != clusterx)
    list1<- append(list1, nrow(INSin))
    list2<- append(list2, nrow(INSout))
    list3<- append(list3, nrow(nonINSin))
    list4<- append(list4, nrow(nonINSout))
    
    df <- data.frame(list2, list4, list1, list3)
    names(df) <- c('INSin','INSout','nonINSin','nonINSout')
    #df <- df %>% mutate(across(where(is.numeric), ~ .x + 1)) #adding 1 to every value to avoid 0
    df2 <- tibble(df)
    
    chi_square_results <- df2 %>% 
      rowwise() %>% 
      mutate(
        test_result = list(perform_chi_square_test(cur_data()))
      ) %>% 
      ungroup() %>% 
      mutate(
        chi_square_statistic = map_dbl(test_result, ~ .x$statistic),
        p_value = map_dbl(test_result, ~ .x$p.value),
        expected_frequencies = map(test_result, ~ .x$expected)
      ) %>% 
      select(-test_result)
    
    pval <- chi_square_results$p_value
    p_adjusted <- p.adjust(pval, method = 'BH')
    chi_square_results$p_adjusted <- p_adjusted
    chi_square_results$x <- as.numeric(row.names(chi_square_results))
    
    finalmatrix[clusterx, as.character(INSx)] <- chi_square_results$p_value[which(chi_square_results$x == clusterx)]
    
  }
}

#matrix with adjusted p-values:
p_vector <- as.vector(finalmatrix)

# Step 2: Apply the p-value adjustment (Benjamini-Hochberg)
p_adjusted_vector <- p.adjust(p_vector, method = "BH")

# Step 3: Reshape the adjusted p-values vector back into the original matrix dimensions
adjusted_p_matrix <- matrix(p_adjusted_vector, nrow = nrow(finalmatrix), ncol = ncol(finalmatrix))
colnames(adjusted_p_matrix) <- allInsertions
rownames(adjusted_p_matrix) <- allClusters



finaldf2 <- as.data.frame(as.table(adjusted_p_matrix))

# Rename the columns for clarity
colnames(finaldf2) <- c("Clusterx2", "INSx2", "pvalue")

```


Plots

```{r}
finaldf2$ID <- paste(finaldf2$Clusterx, finaldf2$INSx)
finaldf$ID <- paste(finaldf$Clusterx, finaldf$INSx)


df_merge <- merge(finaldf, finaldf2,by="ID") 

colnames(df_merge)[colnames(df_merge) == 'Adjusted P-value'] <- 'pvalue'

# Modify the significance column to numeric values
df_merge$significance <- with(df_merge, ifelse(pvalue > 0.05, 0, ifelse(pvalue > 0.02, 1, ifelse(pvalue > 0.01, 2, 3))))

```


```{r}
finaldf2$ID <- paste(finaldf2$Clusterx, finaldf2$INSx)
finaldf$ID <- paste(finaldf$Clusterx, finaldf$INSx)


df_merge <- merge(finaldf, finaldf2,by="ID") 

colnames(df_merge)[colnames(df_merge) == 'Adjusted P-value'] <- 'pvalue'

# Modify the significance column to numeric values
df_merge$logsignificance <- -log10(df_merge$pvalue)
df_merge$Clusterx = as.numeric(df_merge$Clusterx)

# Modify so that the logfolds are max 2 and min -2 and that the significance is maximum 20
df_merge$Log2foldchange <- with(df_merge, ifelse(Log2foldchange > 2, 2, ifelse(Log2foldchange < -2, -2, Log2foldchange)))
df_merge$logsignificance <- with(df_merge, ifelse(logsignificance > 20, 20, logsignificance))


# Plot using the modified significance column
a <- ggplot(df_merge, aes(y = Clusterx, x = INSx, size = logsignificance)) +
  geom_point(aes(color = Log2foldchange)) +
  theme_minimal() +
  labs(title = paste(strain, "clusters and insertion types"),
       x = "Inserition type",
       y = "Cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#  scale_size_continuous(range = c(1, 10)) +             # Adjust the range to control the size of the points for only one plot
  scale_y_reverse(breaks=1:20) +
  scale_size(range = c(1, 15), limits = c(0,20)) +  # this used to compare between plots. to make them comparable, range decides size and limits decides top value
  scale_color_gradient2(low = "blue", mid = "white", high = "brown", midpoint = 0) #Limit sets the top and bottom

a


plotname <- paste(strain, 'plot', sep = "")
assign(plotname, a)


```

If wanted:

Plot, excluding clusters that has a size of 1:

```{r}
clustersizes <- data.frame(table(table$group))
smallclusters <- clustersizes %>% filter(Freq == 1)


if (nrow(smallclusters) > 0) {
clusterout <- c(smallclusters$Var1)
df_merge2 <- subset(df_merge, Clusterx2 != clusterout)

a1 <- ggplot(df_merge2, aes(y = Clusterx, x = INSx, size = logsignificance)) +
  geom_point(alpha = 2, aes(color = Log2foldchange)) +
  theme_minimal() +
  labs(title = paste(strain, "clusters and insertion types"),
       x = "Inserition type",
       y = "Cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#  scale_size_continuous(range = c(1, 5)) +             # Adjust the range to control the size of the points for only one plot
  scale_y_reverse(breaks=1:20) +
  scale_size(range = c(1, 15), limits = c(0,20)) + # this used to compare between plots. to make them comparable, range decides size and limits decides top value
  scale_color_gradient2(low = "blue", mid = "white", high = "brown", midpoint = 0, limits = c(-2, 2))

a1
} else {
a1 <- a
}

a1

```



